In [68]:
import pandas as pd

In [69]:
weather = pd.read_csv("data/Thessaloniki_Weather.csv")

In [70]:
weather

           STATION              NAME        DATE  PRCP  SNWD  TAVG  TMAX  TMIN
0      GRM00016622     MAKEDONIA, GR  1964-01-03   NaN   NaN   1.9   3.9   1.1
1      GRM00016622     MAKEDONIA, GR  1964-01-06   NaN   NaN  -0.2   6.1  -2.8
2      GRM00016622     MAKEDONIA, GR  1964-01-08   NaN   NaN   0.8   7.8  -5.0
3      GRM00016622     MAKEDONIA, GR  1964-01-09   NaN   NaN   2.4   7.2  -1.1
4      GRM00016622     MAKEDONIA, GR  1964-01-13   NaN   NaN  -1.2  10.0  -5.0
...            ...               ...         ...   ...   ...   ...   ...   ...
22881  GRE00155825  THESSALONIKI, GR  2004-09-11   0.0   NaN   NaN  22.8  11.6
22882  GRE00155825  THESSALONIKI, GR  2004-09-12   0.0   NaN   NaN  25.0  11.6
22883  GRE00155825  THESSALONIKI, GR  2004-09-13   0.0   NaN   NaN  26.2  13.4
22884  GRE00155825  THESSALONIKI, GR  2004-09-14   0.0   NaN   NaN  28.4  14.0
22885  GRE00155825  THESSALONIKI, GR  2004-09-15   0.0   NaN   NaN  29.0  16.2

[22886 rows x 8 columns]

In [71]:
#Core weather is determined by data documentation (in data folder)
core_weather = weather[["DATE", "PRCP", "SNWD", "TMAX", "TMIN"]].copy()
core_weather.columns = ["date", "percip", "snow_depth", "max_temp", "min_temp"]
core_weather

             date  percip  snow_depth  max_temp  min_temp
0      1964-01-03     NaN         NaN       3.9       1.1
1      1964-01-06     NaN         NaN       6.1      -2.8
2      1964-01-08     NaN         NaN       7.8      -5.0
3      1964-01-09     NaN         NaN       7.2      -1.1
4      1964-01-13     NaN         NaN      10.0      -5.0
...           ...     ...         ...       ...       ...
22881  2004-09-11     0.0         NaN      22.8      11.6
22882  2004-09-12     0.0         NaN      25.0      11.6
22883  2004-09-13     0.0         NaN      26.2      13.4
22884  2004-09-14     0.0         NaN      28.4      14.0
22885  2004-09-15     0.0         NaN      29.0      16.2

[22886 rows x 5 columns]

In [72]:
#We will deal with null values. 2 main tactics: 1. I put the last value of that column wherever null 2. I put zero

In [73]:
#Show me the percent of each column that is null
core_weather.apply(pd.isnull).sum()/core_weather.shape[0]

date          0.000000
percip        0.227432
snow_depth    0.997116
max_temp      0.283317
min_temp      0.365201
dtype: float64

In [74]:
#Show the number of rows that is null for each column
core_weather.apply(pd.isnull).sum()

date              0
percip         5205
snow_depth    22820
max_temp       6484
min_temp       8358
dtype: int64

In [75]:
#Only 65 days out of 22885 it snowed so we can delete this column
del core_weather["snow_depth"]

In [76]:
core_weather

             date  percip  max_temp  min_temp
0      1964-01-03     NaN       3.9       1.1
1      1964-01-06     NaN       6.1      -2.8
2      1964-01-08     NaN       7.8      -5.0
3      1964-01-09     NaN       7.2      -1.1
4      1964-01-13     NaN      10.0      -5.0
...           ...     ...       ...       ...
22881  2004-09-11     0.0      22.8      11.6
22882  2004-09-12     0.0      25.0      11.6
22883  2004-09-13     0.0      26.2      13.4
22884  2004-09-14     0.0      28.4      14.0
22885  2004-09-15     0.0      29.0      16.2

[22886 rows x 4 columns]

In [77]:
core_weather[pd.isnull(core_weather["percip"])]

             date  percip  max_temp  min_temp
0      1964-01-03     NaN       3.9       1.1
1      1964-01-06     NaN       6.1      -2.8
2      1964-01-08     NaN       7.8      -5.0
3      1964-01-09     NaN       7.2      -1.1
4      1964-01-13     NaN      10.0      -5.0
...           ...     ...       ...       ...
19293  2020-05-11     NaN       NaN       NaN
19569  2021-02-13     NaN       2.7       NaN
19576  2021-02-21     NaN      13.1       NaN
19675  2021-05-31     NaN       NaN       NaN
19926  2022-02-06     NaN       NaN       NaN

[5205 rows x 4 columns]

In [78]:
core_weather["percip"].value_counts()

percip
0.0     14040
0.5       299
1.0       292
0.3       266
2.0       172
        ...
54.1        1
18.7        1
68.1        1
77.0        1
11.8        1
Name: count, Length: 265, dtype: int64

In [79]:
#Most days it had 0 percip so we can replace null values in percip with 0
core_weather["percip"] = core_weather["percip"].fillna(0)

In [80]:
core_weather.apply(pd.isnull).sum()/core_weather.shape[0]

date        0.000000
percip      0.000000
max_temp    0.283317
min_temp    0.365201
dtype: float64

In [81]:
core_weather[pd.isnull(core_weather["max_temp"])]

             date  percip  max_temp  min_temp
15     1964-01-27     0.0       NaN      -7.2
17     1964-01-29     0.0       NaN       NaN
248    1964-12-05     0.0       NaN       NaN
449    1965-06-30    40.9       NaN       NaN
552    1965-10-11     0.0       NaN      13.9
...           ...     ...       ...       ...
20425  2023-06-20     0.0       NaN       NaN
20426  2023-06-21     0.0       NaN       NaN
20428  2023-06-23     0.0       NaN      20.8
20431  2023-06-26     0.0       NaN       NaN
20436  2023-07-01     0.0       NaN       NaN

[6484 rows x 4 columns]

In [82]:
#Min and max temp nulls will be filled up with previous known value
core_weather = core_weather.fillna(method="ffill")

In [83]:
core_weather.apply(pd.isnull).sum()/core_weather.shape[0]

date        0.0
percip      0.0
max_temp    0.0
min_temp    0.0
dtype: float64

In [84]:
core_weather

             date  percip  max_temp  min_temp
0      1964-01-03     0.0       3.9       1.1
1      1964-01-06     0.0       6.1      -2.8
2      1964-01-08     0.0       7.8      -5.0
3      1964-01-09     0.0       7.2      -1.1
4      1964-01-13     0.0      10.0      -5.0
...           ...     ...       ...       ...
22881  2004-09-11     0.0      22.8      11.6
22882  2004-09-12     0.0      25.0      11.6
22883  2004-09-13     0.0      26.2      13.4
22884  2004-09-14     0.0      28.4      14.0
22885  2004-09-15     0.0      29.0      16.2

[22886 rows x 4 columns]

In [85]:
core_weather.dtypes

date         object
percip      float64
max_temp    float64
min_temp    float64
dtype: object

In [88]:
#Turns the date data type (object) into datetime
core_weather["date"] = pd.to_datetime(core_weather["date"])

In [89]:
core_weather.dtypes

date        datetime64[ns]
percip             float64
max_temp           float64
min_temp           float64
dtype: object